name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.monstrous-moonshine.com", custom_domain = true },
  { pattern = "quay.monstrous-moonshine.com", custom_domain = true },
  { pattern = "gcr.monstrous-moonshine.com", custom_domain = true },
  { pattern = "k8s-gcr.monstrous-moonshine.com", custom_domain = true },
  { pattern = "k8s.monstrous-moonshine.com", custom_domain = true },
  { pattern = "ghcr.monstrous-moonshine.com", custom_domain = true },
  { pattern = "cloudsmith.monstrous-moonshine.com", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging-relay.monstrous-moonshine.com", custom_domain = true }


[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
